### ISSUE TITLE
Error on tpmkeys while installing estclient

### ISSUE THREAD

**Issue by anaselhajjaji** [globalsign/est#14]
Hello,

The command go install github.com/globalsign/est/cmd/estclient throws the following error:

github.com/globalsign/tpmkeys /go/pkg/mod/github.com/globalsign/tpmkeys@v1.0.1/key.go:68:23: not enough arguments in call to tpm2.Sign have (io.ReadWriter, tpmutil.Handle, string, []byte, *tpm2.SigScheme) want (io.ReadWriter, tpmutil.Handle, string, []byte, *tpm2.Ticket, *tpm2.SigScheme)

Any idea on how to resolve this?

**Comment by paulgriffiths** [comment]
Hi @anaselhajjaji - thanks for reporting this. This is due to breaking changes in the Google [go-tpm](https://github.com/google/go-tpm) package, which is still in a pre-release state. 

As a short term fix, if you checkout the `go.mod` file again from this repo to revert it to its original state, it should pull the correct version and work for you (that file has probably changed since you cloned the repo as a result of doing a `go get -u`).

In the meantime, I'll push out an update to use the latest version.

**Comment by paulgriffiths** [comment]
Fixed in a760df8a65e19d4a194f9a67db6690b617eaa59c.
