### ISSUE TITLE
Installation recommendation

### ISSUE THREAD

**Issue by mrbluecoat** [globalsign/est#15]
I tried

```
go get github.com/globalsign/est
go install github.com/globalsign/est/cmd/estserver
go install github.com/globalsign/est/cmd/estclient
```

but it gave me these errors:

```
go install github.com/globalsign/est/cmd/estserver
    go/src/github.com/globalsign/est/internal/mockca/ca.go:39:2: cannot find package "github.com/globalsign/pemfile" in any of:
        /usr/lib/go-1.14/src/github.com/globalsign/pemfile (from $GOROOT)
        /root/go/src/github.com/globalsign/pemfile (from $GOPATH)
```

```
go install github.com/globalsign/est/cmd/estclient
cannot find module providing package github.com/globalsign/est/cmd/estclient: working directory is not part of a module
```

Instead, I just used this for installation:

```
go get -u github.com/globalsign/est/cmd/estserver
~/go/bin/estserver -version
go get -u github.com/globalsign/est/cmd/estclient
~/go/bin/estclient version
```

**Comment by mrbluecoat** [comment]
It also took a minute to figure out the help command for the server and client are different:

```
estserver -help
estclient help
```

**Comment by paulgriffiths** [comment]
> It also took a minute to figure out the help command for the server and client are different:
> 
> ```
> estserver -help
> estclient help
> ```

This difference is deliberate, since the client has a command subsystem and the server does not. 

`estclient -help` will give a message showing the correct way to invoke the help system. But `estserver help` will ignore the argument and start the server. For consistency, this should also show a help message. [Separate ticket](https://github.com/globalsign/est/issues/16) raised.

**Comment by toddgaunt-gs** [comment]
Resolved with https://github.com/globalsign/est/pull/26
